services:
  thunders_api:
    image: ${DOCKER_REGISTRY-}thundersapi    
    build:
      context: .
      dockerfile: Thunders_Api/Dockerfile    
    ports:
      - "7106:7106"
    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlpreview
    environment:
      - MSSQL_SA_PASSWORD= leoQueres123
      - ACCEPT_EULA= Y       
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge