services:
  thunders_api:
    image: ${DOCKER_REGISTRY-}thundersapi    
    build:
      context: .
      dockerfile: Thunders_Api/Dockerfile
    environment:
      - Data source=localhost,1433;database=Thunders;TrustServerCertificate=true; User Id=sa;Password=123456;
    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "123456"
      ACCEPT_EULA: "Y"  
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge